default_channels:
- system
- global

default_focus: global

template: '[${color}${channel}§r] ${sender}: ${message}'
pm_template: '§b${sender} -> ${recipient}§r: ${message}'

channels:
  system:
    template: '[${color}${channel}§r] ${message}'
    color: red
  global:
    color: green
  staff:
    color: gold
